services:
  monitoring-python:
    build:
      context: ../../../
      dockerfile: ops/stacks/python/Dockerfile

    image: monitoring-python:v1.0.0
    container_name: monitoring-python
    restart: always

    env_file:
      - ../../services/postgres/.env

    volumes:
      # Solo lectura de logs docker
      # Se monta en modo "ro" (read-only) por motivos de seguridad.
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

      # ❌ ELIMINADO → rompe reproducibilidad
      # - ../../../:/opt/monitoring

      # ❌ ELIMINADO → rompe seguridad y permisos
      # - /var/log:/var/log

      # Acceso al socket de Docker para los scripts de docker_resources.sh y .py - SE INHABILITA POR SEGURIDAD EN LOS MICRO-STACKS
      # - /var/run/docker.sock:/var/run/docker.sock

    healthcheck:
      test: ["CMD", "python3", "scripts/healthcheck.py"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - backend-net  # Red backend (DB + aplicaciones autorizadas)
      - observability-net # Acceso a la red de observabilidad (Loki)
      - restricted-net # Red restringida para servicios específicos (sin acceso a Docker ni logs host)
    environment:
      SMTP_MODE: relay

networks:
  backend-net:
    external: true

  observability-net:
    external: true

  restricted-net:
    external: true
