services:
  monitoring-python:
    build:
      context: ../../../
      dockerfile: ops/stacks/python/Dockerfile

    image: monitoring-python:v1.0.0
    container_name: monitoring-python
    restart: always

    env_file:
      - ../../services/postgres/.env

    volumes:
      # Código del proyecto
      - ../../../:/opt/monitoring

      # Solo lectura de logs docker
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

    healthcheck:
      test: ["CMD", "python3", "scripts/healthcheck.py"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - monitoring-net

networks:
  monitoring-net:
    external: true
