# Imagen para ejecutar scripts Python
FROM monitoring-base

# COPY docker-entrypoint.sh /usr/local/bin/
# RUN chmod +x /usr/local/bin/docker-entrypoint.sh
# ENTRYPOINT ["docker-entrypoint.sh"]

# ENTRYPOINT genérico para ejecutar scripts
ENTRYPOINT ["python3"]
