version: "3.8"

services:
  postgres:
    image: postgres:14.3
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - ../smtp_relay/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monitoring-net
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: "0.5"

volumes:
  postgres-data:
    driver: local

networks:
  monitoring-net:
    external: true
