version: "3.8"

services:
  postgres:
    image: postgres:14.3
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monitoring-net
    # Añadido healthcheck para detectar cuando la BBDD no está operativa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s               # cada cuánto se prueba
      timeout: 10s                # cuánto espera la prueba
      retries: 5                  # cuántos fallos consecutivos para marcar unhealthy
      start_period: 30s           # tiempo inicial de gracia tras arrancar el contenedor
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: "0.5"

volumes:
  postgres-data:
    driver: local

networks:
  monitoring-net:
    external: true
