services:
  smtp-relay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${SMTP_RELAY_CONTAINER_NAME}
    image: monitoring-smtp-relay
    hostname: smtp-relay.local
    env_file:
      - .env
    secrets:
      - smtp_user
      - smtp_pass

#    ports:
#   - "127.0.0.1:2526:587"      # SMTP relay no necesita exposición acceso solo por red docker
#      - "2526:587"              # Puerto expuesto en host (para debug/test manuales SMTP). Se podría eliminar la línea

    environment:
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      RELAYHOST: "[${SMTP_SERVER}]:${SMTP_PORT}"
      FROM_ADDRESS: ${EMAIL_FROM}
      MYNETWORKS: "127.0.0.0/8 172.16.0.0/12 [::1]/128"
      LOG_LEVEL: debug
      ALLOWED_SENDER_DOMAINS: ${EMAIL_DOMAIN}
      ALLOW_EMPTY_SENDER_DOMAINS: "true"

    volumes:
      - ./config:/config:ro
      # Persistencia de logs y debugging
      - smtp_relay_logs:/var/log

      # Redirección de logs a stdout y arranque de Postfix, esto asegura que los logs del contenedor también vayan a stdout (útil para make logs)
    command: ["/scripts/run.sh"]
    healthcheck:
      test: ["CMD-SHELL", "pgrep master || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

    networks:
      - restricted-net  # Red restringida para servicios con egress controlado
    restart: always

secrets:
  smtp_user:
    file: ${SMTP_USER_FILE:-./secrets/smtp_user}
  smtp_pass:
    file: ${SMTP_PASS_FILE:-./secrets/smtp_pass}

networks:
  restricted-net:
    external: true

volumes:
  smtp_relay_logs:
    driver: local
