# Imagen para ejecutar scripts Python
FROM monitoring-base

# Copiar entrypoint específico para la imagen Python
COPY docker-entrypoint.python.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]

